### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by vladfi1** [andrewcooke/pytyp#1]
I recently installed pytyp with `sudo pip3 install pytyp`, but it seems like the only modules installed are `pytyp` and `pytyp.utils` - `pytyp.spec.abcs` and the rest don't exist.

**Comment by andrewcooke** [comment]
huh.  me too.

**Comment by andrewcooke** [comment]
ok, fixed, thanks.  please note that this is really no longer maintained (see note added to docs).  to give some idea of how successful the package was, it appears that it never installed and you are the first person to tell me :(
